// ProjectPlan
export const UPDATE_PROJECT_PLAN = "UPDATE_PROJECT_PLAN";
export const UPDATE_PROJECT_PLAN_DESIGN = "UPDATE_PROJECT_PLAN_DESIGN";

// MyProjects
export const GET_PROJECT_DETAILS_REQUEST = "GET_PROJECT_DETAILS_REQUEST";
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS";
export const GET_PROJECT_DETAILS_ERROR = "GET_PROJECT_DETAILS_ERROR";

// AllProjects
export const GET_ALL_PROJECT_DETAILS_SUCCESS =
  "GET_ALL_PROJECT_DETAILS_SUCCESS";
export const GET_ALL_PROJECT_DETAILS_ERROR = "GET_ALL_PROJECT_DETAILS_ERROR";

// MyTasks
export const GET_MY_TASKS_SUCCESS = "GET_MY_TASKS_SUCCESS";
export const GET_MY_TASKS_ERROR = "GET_MY_TASKS_ERROR";

// AllTasks
export const GET_ALL_TASKS_SUCCESS = "GET_ALL_TASKS_SUCCESS";
export const GET_ALL_TASKS_ERROR = "GET_ALL_TASKS_ERROR";

// UpdateProject
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR";

// ProjectSetUp
export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const SELECTED_PROJECT = "SELECTED_PROJECT";
export const UPDATE_MODE = "UPDATE_MODE";

// User
export const UPDATE_USER = "UPDATE_USER";
export const USER_PROFILE_DATA = "USER_PROFILE_DATA";

//DSBP dropdown 
export const GET_ALL_DSBP_DATA= "GET_ALL_DSBP_DATA";
export const GET_ALL_DSBP_DATA_ERROR = "GET_ALL_DSBP_DATA_ERROR";

