// ProjectPlan
export const GET_PROJECTPLAN_DETAILS_SUCCESS =
  "GET_PROJECTPLAN_DETAILS_SUCCESS";
export const GET_PROJECTPLAN_DETAILS_ERROR = "GET_PROJECTPLAN_DETAILS_ERROR";

// MyProjects
export const GET_PROJECT_DETAILS_SUCCESS = "GET_PROJECT_DETAILS_SUCCESS";
export const GET_PROJECT_DETAILS_ERROR = "GET_PROJECT_DETAILS_ERROR";

// AllProjects
export const GET_ALL_PROJECT_DETAILS_SUCCESS =
  "GET_ALL_PROJECT_DETAILS_SUCCESS";
export const GET_ALL_PROJECT_DETAILS_ERROR = "GET_ALL_PROJECT_DETAILS_ERROR";

// UpdateProject
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const UPDATE_PROJECT_ERROR = "UPDATE_PROJECT_ERROR";

// ProjectSetUp
export const CREATE_NEW_PROJECT = "CREATE_NEW_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const SELECTED_PROJECT = "SELECTED_PROJECT";
export const UPDATE_MODE = "UPDATE_MODE";

// User
export const UPDATE_USER = "UPDATE_USER";
export const USER_PROFILE_DATA = "USER_PROFILE_DATA";
