const DEV = process.env.REACT_APP_API_URL_DEV;
const SIT = process.env.REACT_APP_API_URL_SIT;
const PROD = process.env.REACT_APP_API_URL_PROD;
const url = "https://awflowdev.pg.com";
//const getUrl = "https://awflowdev.pg.com"
export const DEVURL = `${url}/optaplanner/optimize`;
export const SITURL = `${SIT}/prweb/api/ArtworkAgilityFile`;
export const PRODURL = `${PROD}/prweb/api/ArtworkAgilityFile`;
export const AZUREURL = `${url}/optaplanner/azurefile`;
//export const GETURL = `${getUrl}/optaplanner/optimize`;
