export const categories = {
  "Baby Care": [
    "Baby & Feminine Care No Detail",
    "Baby Care Adjacencies",
    "Baby Care NBD",
    "Baby Connected Care",
    "Baby Wipes",
    "Diapers",
  ],
  "Fabric Care": [
    "Bleach",
    "Fabric Care NBD",
    "Fabric Enhancers",
    "Fabric Revitalizer",
  ],
  "Feminine Care": ["Adult Incontinence", "Feminine Care"],
  "Hair Care": [
    "Female Hair Care",
    "Female Hair Care Wella",
    "Female Hair Color",
    "Female Hair Color Wella",
    "Female Prestige Hair",
  ],
  "Home Care": ["Air Care", "Auto Dish", "Cleaning Products", "Dish Care"],
  "Oral Care": ["Dental Floss", "Dentifrice", "Denture Care"],
  "PCC Care": [
    "Childrens Personal Care",
    "Female AP/DO & Body Spray",
    "Female Personal Cleansing",
  ],
  "Shave Care": [
    "Facial Depilatories",
    "Fem Premium BladeRazor System",
    "Female Depilatories",
    "Female Disposable Razor",
    "Female Grooming Skin Care",
    "Female Powered Hair Removal",
    "Female Shave Prep",
  ],
  "Skin Care": [
    "Expert Beauty",
    "Fashion Cosmetics",
    "Fashion Fragrance",
    "Fashion Skin",
    "Female Cosmetics",
    "Female Prestige Skin Care",
    "Female Skin Care",
  ],
  "Unclassified Care": [
    "Alcohols & Related Products",
    "Amine",
    "Antiperspirant/Deodorant Wella",
    "Chemicals NBD",
    "Cleaning Systems",
    "Clock Appliance",
    "Coffee/Hot Beverage Appliance",
    "Fat Substitute",
    "Fatty Acid",
    "Fem Personal Cleansing Wella",
    "Filtration",
    "Food Preparation Appliance",
    "Glycerine",
  ],
};

export const businessUnits = [
  {
    name: "Baby Care",
    code: "BBY",
    categories: [
      {
        Category_Name: "Baby & Feminine Care No Detail",
        code: "BFCND",
      },
      {
        Category_Name: "Baby Care Adjacencies",
        code: "BCA",
      },
      {
        Category_Name: "Baby Care NBD",
        code: "BCN",
      },
      {
        Category_Name: "Baby Connected Care",
        code: "BCC",
      },
      {
        Category_Name: "Baby Wipes",
        code: "BW",
      },
      {
        Category_Name: "Diapers",
        code: "DP",
      },
    ],
  },
  {
    name: "Fabric Care",
    code: "FAB",
    categories: [
      {
        Category_Name: "Bleach",
        code: "BL",
      },
      {
        Category_Name: "Fabric Care NBD",
        code: "FCN",
      },
      {
        Category_Name: "Fabric Enhancers",
        code: "FE",
      },
      {
        Category_Name: "Fabric Revitalizer",
        code: "FR",
      },
    ],
  },
  {
    name: "Feminine Care",
    code: "FEMI",
    categories: [
      {
        Category_Name: "Adult Incontinence",
        code: "AI",
      },
      {
        Category_Name: "Feminine Care",
        code: "FC",
      },
    ],
  },
  {
    name: "Home Care",
    code: "HC",
    categories: [
      {
        Category_Name: "Air Care",
        code: "HC",
      },
      {
        Category_Name: "Auto Dish",
        code: "BV0041",
      },
      {
        Category_Name: "Cleaning Products",
        code: "CP",
      },
      {
        Category_Name: "Dish Care",
        code: "DC",
      },
    ],
  },
  {
    name: "Oral Care",
    code: "OC",
    categories: [
      {
        Category_Name: "Dental Floss",
        code: "DENTF",
      },
      {
        Category_Name: "DENT",
        code: "AD",
      },
      {
        Category_Name: "Denture Care",
        code: "DENC",
      },
    ],
  },
];

export const regionList = [
  {
    name: "ASIA MIDDLE EAST AFRICA",
    code: "AF",
    countries: [
      { name: "Afghanistan", code: "AFG" },
      { name: "Algeria", code: "DZA" },
      { name: "Bahrain", code: "BHR" },
      { name: "Bangladesh", code: "BGD" },
      { name: "Egypt", code: "EGY" }, // Top 5 countries: Afghanistan, Algeria, Bahrain, Bangladesh, Egypt    ]
    ],
  },
  {
    name: "ASIA PACIFIC FOCUS",
    code: "Asia",
    countries: [
      { name: "China", code: "CHN" },
      { name: "India", code: "IND" },
      { name: "Indonesia", code: "IDN" },
      { name: "Japan", code: "JPN" },
      { name: "Malaysia", code: "MYS" },
      // Top 5 countries: China, India, Indonesia, Japan, Malaysia
    ],
  },
  {
    name: "EUROPE ENTERPRISE",
    code: "EUE",
    countries: [
      { name: "France", code: "FRA" },
      { name: "Germany", code: "DEU" },
      { name: "Italy", code: "ITA" },
      { name: "Spain", code: "ESP" },
      { name: "Switzerland", code: "CHE" },
      // Top 5 countries: France, Germany, Italy, Spain, Switzerland
    ],
  },
  {
    name: "EUROPE FOCUS",
    code: "EUF",
    countries: [
      { name: "Belgium", code: "BEL" },
      { name: "Denmark", code: "DNK" },
      { name: "Netherlands", code: "NLD" },
      { name: "Norway", code: "NOR" },
      { name: "Sweden", code: "SWE" },
      // Top 5 countries: Belgium, Denmark, Netherlands, Norway, Sweden
    ],
  },
  {
    name: "GLOBAL",
    code: "GL",
    countries: [
      { name: "Australia", code: "AUS" },
      { name: "Brazil", code: "BRA" },
      { name: "Canada", code: "CAN" },
      { name: "Mexico", code: "MEX" },
      { name: "United States", code: "USA" },
      // Top 5 countries: Australia, Brazil, Canada, Mexico, United States
    ],
  },
  {
    name: "LATIN AMERICA",
    code: "LAM",
    countries: [
      { name: "Argentina", code: "ARG" },
      { name: "Chile", code: "CHL" },
      { name: "Colombia", code: "COL" },
      { name: "Peru", code: "PER" },
      { name: "Venezuela", code: "VEN" },
      // Top 5 countries: Argentina, Chile, Colombia, Peru, Venezuela
    ],
  },
];

export const designScope = [
  { label: "Design Intent", value: "DI" },
  { label: "Regional Design Template", value: "DT" },
  { label: "New Print Feasibility", value: "PF" },
  { label: "Ink Qualification", value: "IQ" },
  { label: "Production Ready Art", value: "PRA" },
  { label: "CIC/GA", value: "CICs" },
  // { label: "POA's", value: "POAs" },
];

export const scaleList = [
  { name: "A", code: "A" },
  { name: "B", code: "B" },
  { name: "C", code: "C" },
  { name: "RBU Customization", code: "RBU Customization" },
];

export const projectTypeList = [
  { name: "Highway", code: "Highway" },
  { name: "TR (Travel Retail)", code: "TR (Travel Retail)" },
  { name: "Cost Saving", code: "C" },
  { name: "Customization", code: "RBU Customization" },
  { name: "BU Promotional", code: "BU Promotional" },
  { name: "Regulatory Change", code: "Regulatory Change" },
  { name: "Commercial Initiative", code: "Commercial Initiative" },
  { name: "Technical Change", code: "Technical Change" },
];

export const Tier = [
  { name: "T0 Premium", code: "T0Premium" },
  { name: "T0 Taped", code: "T0Taped" },
  { name: "T0 Wipes", code: "T0Wipes" },
  { name: "T1 Pants", code: "T1Pants" },
  { name: "T1 Premium", code: "T1Premium" },
  { name: "T1 Taped", code: "T1Taped" },
  { name: "T1 Wipes", code: "T1Wipes" },
  { name: "T2 Pants", code: "T2Pants" },
  { name: "T2 Taped", code: "T2Taped" },
  { name: "T2 Wipes", code: "T2Wipes" },
  { name: "T3 Taped", code: "T3Taped" },
  { name: "T3 Wipes", code: "T3Wipes" },
  { name: "Bedmats", code: "Bedmats" },
  { name: "Splashers", code: "Splashers" },
  { name: "Wipes", code: "Wipes" },
  { name: "Underjams", code: "Underjams" },
];
export const ProductionStrategy = [
  { name: "CIC matrix", code: "CICmatrix" },
  { name: "CIC & follower", code: "CIC&follower" },
  { name: "SAR", code: "SAR" },
  { name: "DTP", code: "DTP" },
];
export const brandList = [
  {
    Brand_Name: "Charlie Banana",
    code: "BV0102",
  },
  {
    Brand_Name: "Pampers",
    code: "J29",
  },
  {
    Brand_Name: "All Clean",
    code: "BV0121",
  },
  {
    Brand_Name: "Lines",
    code: "D76",
  },
  {
    Brand_Name: "Cutie",
    code: "H61",
  },
  {
    Brand_Name: "Dodot",
    code: "H66",
  },
  {
    Brand_Name: "Luvs",
    code: "J15",
  },
  {
    Brand_Name: "Linidor",
    code: "LNDR",
  },
  {
    Brand_Name: "Minor Brands",
    code: "MB",
  },
  {
    Brand_Name: "Lumi",
    code: "CC7863",
  },
  {
    Brand_Name: "Pampers Kandoo",
    code: "JJM02",
  },
  {
    Brand_Name: "Dodot Kandoo",
    code: "JJM03",
  },
  {
    Brand_Name: "Ninjamas",
    code: "BV0098",
  },
  {
    Brand_Name: "All Good",
    code: "CC3334",
  },
  {
    Brand_Name: "Dodotis",
    code: "H67",
  },
  {
    Brand_Name: "Babysan",
    code: "H9",
  },
  {
    Brand_Name: "Mammi",
    code: "J18",
  },
  {
    Brand_Name: "Liberty",
    code: "LIB",
  },
  {
    Brand_Name: "Disco",
    code: "TA31",
  },
  {
    Brand_Name: "Ausonia",
    code: "D75",
  },
  {
    Brand_Name: "Ambi Pur",
    code: "AP",
  },
  {
    Brand_Name: "Attento",
    code: "ATNT",
  },
  {
    Brand_Name: "9 Elements",
    code: "BV0088",
  },
  {
    Brand_Name: "NBD.",
    code: "BV0090",
  },
  {
    Brand_Name: "Diversified Chemicals Techn",
    code: "CC0267",
  },
  {
    Brand_Name: "Home Made Simple",
    code: "CC892",
  },
  {
    Brand_Name: "Downy",
    code: "DWNY",
  },
  {
    Brand_Name: "Febreze",
    code: "FBRZ",
  },
  {
    Brand_Name: "Private Label",
    code: "KM102",
  },
  {
    Brand_Name: "Lenor",
    code: "LENR",
  },
  {
    Brand_Name: "Sanytol",
    code: "NC1620",
  },
  {
    Brand_Name: "Ariel",
    code: "V14",
  },
  {
    Brand_Name: "Luster Professional",
    code: "CC720",
  },
  {
    Brand_Name: "Deepio Professional",
    code: "CJG79PRO",
  },
  {
    Brand_Name: "Clean Quick Professional",
    code: "CLNQ1",
  },
  {
    Brand_Name: "Cream Suds Professional",
    code: "CRSD1",
  },
  {
    Brand_Name: "Ace",
    code: "V04",
  },
  {
    Brand_Name: "All",
    code: "V01",
  },
  {
    Brand_Name: "Ambi Pur Professional",
    code: "APPRO",
  },
  {
    Brand_Name: "Antikal",
    code: "ANTK",
  },
  {
    Brand_Name: "Antikal Professional",
    code: "ANTKPRO",
  },
  {
    Brand_Name: "Ava",
    code: "AVA",
  },
  {
    Brand_Name: "Ava Mat",
    code: "M19",
  },
  {
    Brand_Name: "Ayudin",
    code: "AYDN",
  },
  {
    Brand_Name: "Base Line",
    code: "BV0045",
  },
  {
    Brand_Name: "Battle",
    code: "BAT",
  },
  {
    Brand_Name: "Baleno",
    code: "BAL",
  },
  {
    Brand_Name: "Blue Planet",
    code: "BV0141",
  },
  {
    Brand_Name: "Blesk",
    code: "BLSK",
  },
  {
    Brand_Name: "Biz",
    code: "BZBL",
  },
  {
    Brand_Name: "Brigade",
    code: "BRGD",
  },
  {
    Brand_Name: "Buena Vibra (Maestro Limpio)",
    code: "BVML",
  },
  {
    Brand_Name: "Buena Vibra (Mr Clean)",
    code: "BVMC",
  },
  {
    Brand_Name: "Bowl Quick",
    code: "BWQK",
  },
  {
    Brand_Name: "Cierto",
    code: "CRTO",
  },
  {
    Brand_Name: "CLOSA",
    code: "BV0013",
  },
  {
    Brand_Name: "Cascade",
    code: "CSCD",
  },
  {
    Brand_Name: "Cascade Professional",
    code: "CSCD1",
  },
  {
    Brand_Name: "Cinch",
    code: "CNCH",
  },
  {
    Brand_Name: "Cream Suds",
    code: "CRSD",
  },
  {
    Brand_Name: "Cream Suds Professional",
    code: "CRSD1",
  },
  {
    Brand_Name: "Cristal",
    code: "CRST",
  },
  {
    Brand_Name: "Comet",
    code: "T4",
  },
  {
    Brand_Name: "Comet Professional",
    code: "T41",
  },
  {
    Brand_Name: "Deepio",
    code: "CJG79",
  },
  {
    Brand_Name: "Dawn",
    code: "DAWN",
  },
  {
    Brand_Name: "Dawn Professional",
    code: "DAWNPRO",
  },
  {
    Brand_Name: "Dax",
    code: "C5",
  },
  {
    Brand_Name: "Don Limpio",
    code: "TA11",
  },
  {
    Brand_Name: "Don Limpio Professional",
    code: "TA11PRO",
  },
  {
    Brand_Name: "Dreft",
    code: "DRFD",
  },
];

export const PrinterList = [
  "ALL4LABELS ITALY NMS S R L~15144637",
  "MCC CARDIFF LTD~10073106",
  "X LABEL ROMANIA SRL~15314268",
  "MODEL KRAMP GMBH~15228466",
  "PRIVATE JOINT STOCK CO RUBEZHNOYE~15045747",
  "ALL4LABELS ERFURT GMBH & CO KG~15206299",
  "CORBUS EUROPE LTD~15305162",
  "ALBEA WARSAW SP ZOO~15252808",
  "SMURFIT KAPPA ITALIA SPA~15205057",
  "AMCOR FLEXIBLES NEOCEL EMBALAGENS~15337983",
  "AMCOR FLEXIBLES BENELUX DIVISION OF~10046557",
  "MULTI COLOR CORP CORPORATE~20513225",
  "EDELMANN PACKAGING MEXICO SA DE CV~15235913",
  "BLP NORTHERN LTD~60063179",
  "ALL4LABELS HAMBURG GMBH & CO KG~15039657",
  "ALL4LABELS LUEBBECKE GMBH~15235053",
  "SPI 2~15266486",
  "FLEXICON AG~10005800",
  "COLLOTYPE LABELS IRELAND LTD~15141387",
  "RAJKUMAR OFFSET PRINTERS PVT LTD~15097621",
  "MCC POLSKA SA~15287551",
  "FIRST CO. FOR INDUSTRIAL~15194718",
  "HB PRINT SRO~20570976",
  "EPL POLAND SP ZOO~15301371",
  "MONDI HALLE GMBH~10100662",
  "CPC COTENTIN~15068073",
  "DRUKARNIA WIST SP Z OO~20624633",
  "KOROZO AMBALAJ SAN VE TIC AS KOROZO~15149304",
  "CONTRACOLADOS DEL CENTRO SL~63010622",
  "ENTRE SRO~15077220",
  "GRAFICADISPLAY SRL~15320151",
  "ITELLA~74203015",
  "GPI POZNAN SP ZOO~20589497",
  "SAICA PACK TURKEY AMBALAJ SAN AS~15304021",
  "NEUPACK POLSKA SP ZOO~20618853",
  "JOH LEUPOLD GMBH & CO KG~15152834",
  "SMURFIT KAPPA OBALY STUROVO AS~15170345",
  "MULTI COLOR WARSAW POLAND S A~15275949",
  "DRUKARNIA DAKO KOZIOL I WSPOLNICY~15275587",
  "THIMM OBALY KS THE HIGHPACK CO~15145497",
  "MDV INDUSTRIES LTD~15316860",
  "DS SMITH PACKAGING DEUTSCHLAND~15298265",
  "LLC IMPRESS~15226467",
  "MM PACKAGING SCHILLING GMBH~10100253",
  "DS SMITH PACKAGING CONTOIRE HAMEL~15056364",
  "OKIL SATO CO LTD~15311715",
  "OBEIKAN PRINTING & PACKAGING CO~20107619",
  "NEUPACK GESELLSCHAFT MBH~15049046",
  "NEKICESA PACKAGING SL~15244482",
  "VG NICOLAUS GMBH & CO KG~15216890",
  "COMMUNISIS HELLAS SERVICES~15284576",
  "MCC POZNAN SP. Z O.O.~15191742",
  "POPLART KFT~15181297",
  "SMURFIT KAPPA ESPANA SA~15245255",
  "KOROZO DIS TICARET A S~15299319",
  "MCC NANTES FRANCE SAS~15044085",
  "ELIF PLASTIK AMB SAN VE TIC AS~10006449",
  "KAPPA PACKAGING SPA~15007642",
  "FUJI SEAL POLAND SP Z O O~15308533",
  "AMCOR FLEXIBLES ZLOTOW SP ZOO~15112845",
  "COVERIS FLEXIBLES ANGOULEME FRANCE~15163380",
  "GRAPHIC PACKAGING INTERNATIONAL~15245093",
  "MMP NEUPACK POLSKA SP ZOO~15239726",
  "THIMM DISPLAY SERVICE GMBH~15259158",
  "ELIF GLOBAL PACKAGING S A E~15301397",
  "VAN GENECHTEN BIERMANS NV~10100297",
  "CROWN PACKAGING DISTRIBUTION UK LTD~20590196",
  "DOT2DOT SA~78504091",
  "MULTI COLOR HANN MUENDEN GERMANY~15350819",
  "EDELMANN HUNGARY PACKAGING ZRT~15308904",
  "MCC LIVERPOOL~15271868",
  "SCHUMACHER PACKAGING SP Z O O~15299465",
  "PJSC GRAPHIA UKRAINA~15339040",
  "LIC PACKAGING SPA~15340647",
  "HUHTAMAKI INDIA LTD~15328725",
  "SMURFIT KAPPA UK LTD~15291280",
  "DS SMITH PACKAGING LTD~15021049",
  "EDELMANN PHARMADRUCK GMBH~15294041",
  "ETIKETTENFABRIK ERHARD KUECHLER~20592652",
  "CHENNAI MICRO PRINT PVT LTD~15225441",
  "ONDAL FRANCE S A R L~20637626",
  "VTO TEST SUPPLIER 1~20514297",
  "MARKEM IMAJE SAS~10054324",
  "ROMPRIX EXIM~20578573",
  "COMMUNISIS UK LTD~20586029",
  "COMMUNISIS ROMANIA SRL~15300657",
  "360 CO PACKING SRL~15284872",
  "LEADING EDGE LABELS LTD~15249645",
  "MONDI SZADA KFT~10101739",
  "HANGZHOU ALL FOR LABELS PACKAGING~15292943",
  "DS SMITH PACKAGING DEUTSCHLAND~15324319",
  "REDBOX SRL~15237163",
  "DS SMITH POLSKA SP Z O O~15305294",
  "AR PACKAGING BERLIN FOOD GMBH~15163025",
  "DS SMITH PACKAGING NORD EST~15255440",
  "DS SMITH PACKAGING DEUTSCHLAND~20634291",
  "VG POLSKA SP ZOO~15060825",
  "BALL AEROSOL PACKAGING UK LTD~10052958",
  "SMURFIT KAPPA GMBH~15177613",
  "FAIRFORM MFG CO LTD~20586673",
  "EURODISPLAY DESIGN IN PROGRESS SRL~64012357",
  "ZOBELE BULGARIA EOOD~15220718",
  "CART ONE S R L~15351317",
  "CHEMES M SZPERLINSKI SP ZOO~15269980",
  "ALL4LABELS ROMANIA S.R.L.~15326394",
  "SHANGHAI JIELONG ART PRINTING CO~20625215",
  "SMURFIT KAPPA FRANCE SAS~15082066",
  "COPIMAD~20102501",
  "JOINT STOCK CO SAINT PETERSBURG~20627898",
  "SMURFIT KAPPA CZECH SRO~20569208",
  "ANHUI ZIJIANG COMPOSITE MATERIAL~15362646",
  "MODEL KRAMP GMBH~10079808",
  "CCL LABEL LTD~20574292",
  "MMM AGENCY SARL~15146511",
  "JSC GOTEK PRINT~15311954",
  "REHMPACK PVT LTD~15312848",
  "SHREE PACKERS MP PVT LTD~15102550",
  "MULTI COLOR LABELS IRELAND LTD~10073919",
  "SAICA PACK S L PLANTA VALENCIA~15317099",
  "ZERMATT S A~10101649",
  "COSMINT SPA~10005174",
  "ESSEL PROPACK MISR FOR ADVANCED~15315671",
  "AJANTA PACKAGING FZC~15304036",
  "KANG NA HSIUNG ENTERPRISE SHANGHAI~10028481",
  "CONSTANTIA TOBEPAL SLU~15240488",
  "DS SMITH PACKAGING DEUTSCHLAND~15321054",
  "PAYER ELECTRIC PERSONAL CARE~15248165",
  "SB PACKAGINGS LTD~15021442",
  "HAYCO DOMINICAN REPUBLIC CO SRL~15315285",
  "I & RG IMPRIMERIE~10101064",
  "COVERIS FLEXIBLES EGYPT LTD~15296158",
  "FUJI SEAL EUROPE SAS~15139375",
  "LLC LIMATONUPAKOVKA~15196646",
  "LLC MM POLYGRAFOFORMLENIE~15134448",
  "OKIL LLC~15077839",
  "HI P SHANGHAI HOUSING APPLIANCE CO~20581863",
  "FUJI SEAL BV~15364778",
  "MORAVIA CANS AS~15031372",
  "FUJI SEAL EUROPE LTD~10100587",
  "ILLERT GMBH & CO KG~20592692",
  "UFLEX LTD UNIT II~15263243",
  "CCL LABEL S P Z O O~15143903",
  "PARKSONS PACKAGING LTD~15322513",
  "ERO ETIKETT GMBH~20571110",
  "UNITED CARTON INDUSTRIES CO~20107683",
  "SMURFIT KAPPA CARTOMILLS~10006722",
  "PARKSONS PACKAGING LTD~15248569",
  "MAX AARTS BV~15352683",
  "MONDI BAD RAPPENAU GMBH~10100080",
  "LEUNISMAN GMBH~20571070",
  "MULTI PACKAGING SOLUTIONS TCZEW SP~15169633",
  "PAHARPUR 3P PVT LTD~15344335",
  "NIGERIAN BAG MANUFACTURING~20602223",
  "SIGMA PACKAGING~15285383",
  "STI GUSTAV STABERNACK GMBH~10101190",
  "BALL AEROCAN CZ S R O~15322034",
  "DS SMITH PACKAGING - ROANOKE~15282410",
  "SHUBHAM TEXPLAST PVT LTD~15317052",
  "GERMARK SA~10059239",
  "CYDEN LTD~15253449",
  "COSMEWAX S A~20585969",
  "GORSEL SANATLAR MATBAACILIK AMBALAJ~15239294",
  "ESSENTRA PACKAGING IRELAND LTD~15310345",
  "TATRA SPRING POLSKA SP Z OO~15318418",
  "CHI NHANH CONG TY TNHH OJITEX VIET~15356233",
  "SUZHOU YUTO PRINTING CO LTD~15340392",
  "FR SCHIETTINGER KG~20571004",
  "JOS HILLEKAMP GMBH & CO KG~15119209",
  "MULTI PACKAGING SOLUTIONS BIALYSTOK~15337332",
  "PARAGON IDENTIFICATION~15134955",
  "SHENZHEN YUTO PACKAGING TECHNOLOGY~20625954",
  "SAICA PACK SL~15229570",
  "SHANGHAI NEW ISLAND PACKAGING~20625209",
  "SIGNAL SP ZOO~10021662",
  "EPL POLAND SP ZOO~15330508",
  "TOSCANA ONDULATIS S P A DIV~15310751",
  "SMURFIT SOCAR~15101310",
  "VELVIN PAPER PRODUCTS~15318666",
  "LIBRA ARTES GRAFICAS SA~15056155",
  "MAYR MELNHOF PACKAGING AUSTRIA GMBH~10103140",
  "HINOJOSA PACKAGING S L~15313912",
  "AMCOR FLEXIBLES REFLEX SP ZOO~15249505",
  "UFLEX LTD~15214158",
  "SUN PACKAGING CO LLC~15229956",
  "RIALTO ENTERPRISES PVT LTD~20584381",
  "SADE OFSET MATBAACILIK AMB MLZ BURO~20585014",
  "PLASTICOS ESPANOLES SA~10100840",
  "DEVINEAU SAS~15226747",
  "SHRINATH ROTO PACK PVT LTD~15306621",
  "THIMM DISPLAY GMBH~20145213",
  "VERTICE GLOBAL PVT LTD~15337201",
  "UNITED CARTON INDUSTRIES CO~15327159",
  "IPE INDUSTRIA GRAFICA SLU~20635161",
  "LLC MONDI ARAMIL~15330236",
  "VG NICOLAUS GMBH~15361647",
  "PINGHU TIANYANG PRINTING CO LTD~20629506",
  "EPL DEUTSCHLAND GMBH & CO. KG~15088580",
  "GHARB PAPIER & CARTON~20102332",
  "EMIRATES PRINTING PRESS LLC~15209278",
  "LTD ALBA PLUS~15316180",
  "COLEP CONSUMER PRODUCTS POLSKA SP~15141686",
  "OLYMPUS PRINT GROUP LTD~15061376",
  "CEBAL UK LTD~10101414",
  "LITO OFFSET COMERCIAL SA DE CV~20583808",
  "DECOMATIC SA~10102700",
  "TECHNIMARK PRECISION MOLDING SUZHOU~15267084",
  "DHANLAKSHMI PACKAGING INDUSTRIES~15338288",
  "PACMAN EGYPT~15168309",
  "SMURFIT KAPPA ESPANA SA~10100909",
  "TFP SP ZOO~15353085",
  "SOCOPOL SP ZOO~15281969",
  "GROUPE CMCP SA~20102289",
  "CCL LABEL GMBH~15122618",
  "NUTECH PACKAGINGS PROP SUNNY~15320454",
  "ELANDERS HUNGARY KFT~15301784",
  "DS CONTAINERS INC~15185965",
  "AMCOR FLEXIBLES INDIA PVT LTD~15327372",
  "YUEN FOONG YU PAPER ENTERPRISE~15255394",
  "SMURFIT KAPPA CHELMSFORD~15206571",
  "NASR PACKAGING & PRINTING CO~20107756",
  "BERRY GLOBAL INC~15217035",
  "TRUVANT EUROPE SP Z O O~15216126",
  "FARMOL SPA~15095572",
  "LLC WITH FOREIGN INVESTMENT UKRAINE~15170796",
  "CCL LABEL~15183943",
  "SCHLEUNUNGDRUCK GMBH~20594354",
  "PREMIER PAPER PACKAGING A UNIT OF~15265410",
  "PANASONIC WANBAO APPLIANCES BEAUTY~15184578",
  "CLONDALKIN PHARMA & HEALTHCARE~15210834",
  "MAIN STREET 1301 PTY LTD~15310897",
  "JOINT STOCK COMPANY MOSCOW~15301303",
  "MULTI PACKAGING SOLUTIONS BELFAST~20630859",
  "CARTONNAGES DU RIF~15043944",
  "GLOBAL PACKAGING INC~15135426",
  "SMURFIT KAPPA~15206027",
  "TIANJIN ZRP PRINTING TECHNOLOGY~15307678",
  "NSD INTERNATIONAL SPECIAL PRODUCTS~15046451",
  "PRECO CORPORATION~20610124",
  "HOPI SRO~15268922",
  "FUJI SEAL GERMANY GMBH~10040739",
];

export const PrinterProcessList = [
  "2 Colour Spot",
  "Cold Foil",
  "Digital",
  "Dry Offset",
  "Flexo 133lpi Kodak",
  "Flexo 133lpi",
  "Flexo 136lpi",
  "Flexo 150lpi Kodak",
  "Flexo 150lpi",
  "Flexo HD",
  "Flexo Post Print",
  "Flexo Pre Print",
  "Flexo",
  "Flexo/Digital",
  "Flexo/Gravure",
  "Flexo/Gravure/Offset",
  "Flexo/Offset",
  "Flexo/Offset/Silk Screen",
  "Flexo/Offset/Silkscreen",
  "Flexo/Silk Screen",
  "Gravure",
  "Gravure/Offset",
  "HAPA Ink Jet Printer",
  "Heat Transfer",
  "Hot Foil",
  "Ink Jet",
  "Letter Press/Silk Screen",
  "Letterpress",
  "Letterpress/Screen/Flexo",
  "Offset (Litho)",
  "Offset",
  "Offset/Digital",
  "Offset/Silk Screen",
  "Pad Printing",
  "Primography",
  "RIGHT SIZED PRINTING",
  "Relief Printing",
  "Silk Screen",
  "Thermic Film",
];
export const SubstrateList = [
  "Cartonboard-Aseptic Composite Board",
  "Cartonboard-Coated Bleached-SBS-SBB-GZ",
  "Cartonboard-Coated Unbleached Kraft-CUK",
  "Cartonboard-Coated WLC CCNB GD GT CRB",
  "Cartonboard-Coated-Wax",
  "Cartonboard-Folding Box Board-FBB-GC",
  "Cartonboard-Laminated",
  "Cartonboard-Other",
  "Cartonboard-Uncoated URB GK CB",
  "Corrugated-Brown",
  "Corrugated-Laminated",
  "Corrugated-Other",
  "Corrugated-Wax Coated",
  "Corrugated-White Liner",
  "Fiber-Antislip Coated Paper",
  "Fiber-Coated Paper",
  "Fiber-Molded Pulp",
  "Fiber-Other",
  "Fiber-Uncoated Paper",
  "Fiber-Wax Coated Paper",
  "Fiber-Wood-Dimensional Lumber",
  "Glue or Adhesive",
  "Inks and Coatings",
  "Laminate-other",
  "Metal-aluminum",
  "Metal-steel",
  "Metals-Other",
  "Metals-Tinplate",
  "Natural materials-Glass",
  "Natural materials-Other",
  "Natural materials-Wax",
  "Plastics-BioBased PE-PolyEthylene",
  "Plastics-BioBased PET-PolyEthylene Terephtalate",
  "Plastics-BioBased PP-PolyPropylene",
  "Plastics-Biopolymer PHA PolyHydroxyAlkanoate",
  "Plastics-Biopolymer PLA PolyLactic Acid",
  "Plastics-EPS ExpandedPolyStyrene",
  "Plastics-EVOH Ethylene Vinyl Alcohol",
  "Plastics-HDPE-High Density PolyEthylene",
  "Plastics-LDPE LowDensity PolyEthylene",
  "Plastics-LLDPE LinearLowDensity PolyEthylene",
  "Plastics-MDPE MediumDensity PolyEthylene",
  "Plastics-Others",
  "Plastics-PA PolyAmides-Nylon",
  "Plastics-PC PolyCarbonates",
  "Plastics-PET or PETE-PolyEthylene Terephtalate",
  "Plastics-PETG PolyEthylene Terephthalate Glycol",
  "Plastics-PP-PolyPropylene",
  "Plastics-PS PolyStyrene",
  "Plastics-PVA-PolyVinyl Alcohol",
  "Plastics-PVC-PolyVinyl Chloride",
  "Plastics-Silicone- less dense than water",
  "Plastics-Silicone- more dense than water",
  "Plastics-Thermoplastics-POM-Acetal",
  "Plastics-Thermoplastics-SAN-ABS",
  "Plastics-TPE Thermoplastic Elastomer",
  "Rubber-SBR Styrene Butadiene Rubber",
  "Synthetic Materials-Oils",
];
