export const RoleUser = {
  users: [
    {
      username: "Izabela",
      password: "iza123",
      userid: "@iza123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "Karol",
      password: "karol123",
      userid: "@karol123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "Luca",
      password: "luca123",
      userid: "@luca123",
      role: "TaskOwner",
      bu: "BABY",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "Cherry",
      password: "cheryy123",
      userid: "@cherry123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe",
      permissions: ["read", "view"],
    },
    {
      username: "Nora",
      password: "nora123",
      userid: "@nora123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "Gabriel",
      password: "gabriel123",
      userid: "@gabriel123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe",
      permissions: ["read", "view"],
    },
    {
      username: "pg",
      password: "pg123",
      userid: "@pg123",
      role: "TaskOwner",
      bu: "Baby Care",
      region: "Europe",
      permissions: ["read", "view"],
    },
    {
      username: "Deboleena",
      password: "deb123",
      userid: "@deboleena",
      role: "PM",
      bu: "BBY",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },


    {
      username: "Deboleena",
      password: "deb123",
      userid: "@deboleena",
      role: "PM",
      bu: "BBY",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },

  ],
};
