export const RoleUser = {
  users: [
    {
      username: "malashree",
      password: "mala123",
      userid: "koley.mk",
      role: "TaskOwner",
      bu: "FAB",
      region: "EUROPE ENTERPRISE",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "pusan",
      password: "pusan123",
      userid: "chatterjee.pc.2",
      role: "TaskOwner",
      bu: "FAB",
      region: "EUROPE ENTERPRISE",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "Izabela",
      password: "iza123",
      userid: "@iza123",
      role: "TaskOwner",
      bu: "FAM",
      region: "EUROPE ENTERPRISE",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "Karol",
      password: "karol123",
      userid: "@karol123",
      role: "TaskOwner",
      bu: "FAB",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "Luca",
      password: "pg123",
      userid: "@luca123",
      role: "ProjectManager",
      bu: "FAB",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "Cherry",
      password: "cheryy123",
      userid: "@cherry123",
      role: "TaskOwner",
      bu: "OC",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "Nora",
      password: "nora123",
      userid: "@nora123",
      role: "TaskOwner",
      bu: "FAB",
      region: "EUROPE ENTERPRISE",
      permissions: ["create", "read", "update", "delete"],
    },
    {
      username: "Gabriel",
      password: "gabriel123",
      userid: "@gabriel123",
      role: "TaskOwner",
      bu: "OC",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
    {
      username: "pg",
      password: "pg123",
      userid: "@pg123",
      role: "TaskOwner",
      bu: "BBY",
      region: "EUROPE ENTERPRISE",
      permissions: ["read", "view"],
    },
  ],
};
